// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Integrador.Models
{
    public partial class ActualizarClinicasResult
    {
        public int id { get; set; }
        public string Clinica_nombre { get; set; }
        public string direccion { get; set; }
        public string ruc { get; set; }
        public byte? estado { get; set; }
    }
}
