// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Integrador.Models;

public partial class Especialidad
{
    public int Id { get; set; }

    public string ENombre { get; set; }

    public string EDescripcion { get; set; }

    public string EArea { get; set; }

    public string ECodigo { get; set; }

    public byte Estado { get; set; }

    public virtual ICollection<DotorEspecialidad> DotorEspecialidads { get; set; } = new List<DotorEspecialidad>();

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}