// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Integrador.Models
{
    public partial class ListarTipoAtencionResult
    {
        public int id { get; set; }
        public string t_descripcion { get; set; }
    }
}
