// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Integrador.Models
{
    public partial class ListarReservasResult
    {
        public int id { get; set; }
        public DateTime fecha { get; set; }
        public string sintomas { get; set; }
        public int estado { get; set; }
        public int us_id { get; set; }
        public int doc_id { get; set; }
        public int at_id { get; set; }
        public int cli_id { get; set; }
        public int especialidad_id { get; set; }
    }
}
