// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Integrador.Models
{
    public partial class ListarReservaResult
    {
        public DateTime fecha { get; set; }
        public int estado { get; set; }
        public int usId { get; set; }
        public string usNombre { get; set; }
        public string usApellido { get; set; }
        public int docId { get; set; }
        public string docNombre { get; set; }
        public string docApellido { get; set; }
        public int atId { get; set; }
        public string atDescripcion { get; set; }
        public int cliId { get; set; }
        public string cliNombre { get; set; }
        public string cliDireccion { get; set; }
    }
}
