// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Integrador.Models
{
    public partial class ListarEspecialidadesResult
    {
        public int id { get; set; }
        public string e_nombre { get; set; }
        public string e_descripcion { get; set; }
        public string e_area { get; set; }
        public string e_codigo { get; set; }
    }
}
