// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Integrador.Models;

public partial class Reserva
{
    public int Id { get; set; }

    public DateTime Fecha { get; set; }

    public string Sintomas { get; set; }

    public int Estado { get; set; }

    public int UsId { get; set; }

    public int DocId { get; set; }

    public int AtId { get; set; }

    public int CliId { get; set; }

    public int EspecialidadId { get; set; }

    public virtual TipoAtencion At { get; set; }

    public virtual Clinica Cli { get; set; }

    public virtual Usuario Doc { get; set; }

    public virtual Especialidad Especialidad { get; set; }

    public virtual Usuario Us { get; set; }
}