// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Integrador.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string TipoDocumento { get; set; }

    public string Dni { get; set; }

    public string Correo { get; set; }

    public string Username { get; set; }

    public string Psw { get; set; }

    public string Celular { get; set; }

    public byte Estado { get; set; }

    public int? RolUser { get; set; }

    public virtual ICollection<ClinicaUsuario> ClinicaUsuarios { get; set; } = new List<ClinicaUsuario>();

    public virtual ICollection<DotorEspecialidad> DotorEspecialidads { get; set; } = new List<DotorEspecialidad>();

    public virtual ICollection<Ficha> FichaDocs { get; set; } = new List<Ficha>();

    public virtual ICollection<Ficha> FichaUsus { get; set; } = new List<Ficha>();

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual ICollection<Reserva> ReservaDocs { get; set; } = new List<Reserva>();

    public virtual ICollection<Reserva> ReservaUs { get; set; } = new List<Reserva>();

    public virtual Rol RolUserNavigation { get; set; }
}